<?php /** @var $block \TCK\Blog\Block\PostList */ ?>
<h1><?php echo __('Ultimas noticias') ?></h1>
<ul class="blog-post-list">
    <?php /** @var $post \TCK\Blog\Model\Post */ ?>
    <?php foreach ($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="<?php echo $post->getUrl() ?>"><?php echo $post->getTitle() ?></a>
            </h3>

            <div class="blog-post-item-content">
                <?php echo $post->getContent(); ?>
            </div>

            <div class="blog-post-item-meta">
                <strong><?php echo __('Creado:') ?></strong> <?php echo $post->getCreationTime() ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>