<?php
/** @var $block \TCK\Blog\Block\PostView */
/** @var $post \TCK\Blog\Model\Post */
$post = $block->getPost();
$date=$post->getCreationTime();
$date=explode("-", $date);
$day=explode(" ",$date[2]);
$months=array("january", "february", "march","april","may","june","july","august","september","october","november","december");
$month=intval($date[1])-1;
$date_txt=$day[0]." de ".$months[$month]." de ".$date[0];
?>
<h1 class="blog-post-item-title"><?php echo $post->getTitle() ?></h1>

<div class="blog-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="blog-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $date_txt; ?>
</div>
